---
# TITLE
dct_title_s: Pre-K to 12 Schools, Rhode Island, 2024

# DESCRIPTION
dct_description_sm:
- This is a point layer of all preschools, elementary schools, and high schools in Rhode Island. It was created by geocoding addresses from the Rhode Island Department of Education's School Directory against the Rhode Island Department of Transportation's E911 Sites Address Locator. The following school directory reports were aggregated to form the basis for the dataset - District Profile (public schools), State Operated Schools, Career & Technical Schools, Charter Schools, Schools For Children With Disabilities, Catholic Schools, Independent Private Schools, and Private Educational Programs For Very Young Children. Records for administrative offices, schools outside the state, and duplicates of facility records for individual school officials were expunged, and columns with names of officials and contact information were removed. The coordinates for each school are in the Rhode Island State Plane Zone in feet, and represent the center of the first parcel that was returned for the geocoded school address. Addresses that could not initially be matched were modified to achieve matches; the add_orig column contains the original RIDE address for non-matching records. There are two identifiers that were generated by the RI Dept of Education, org_ID and code. These codes are unique with the exception of org 1521 (Metropolitan Regional Career and Technical Center), which has three distinct locations with the same code. There are also fields that indicate the type of school (subtype ID and name) and range of grade levels. A Python script was written to automate data processing and geocoding. This layer was created by the Brown University Library as part of the Ocean State Spatial Database (OSSDB) project, a resource designed for basic geographic analysis and thematic mapping within the State of Rhode Island, and to provide updated layers for the Rhode Island Geographic Information System (RIGIS) data repository.

# LANGUAGE
dct_language_sm:
- eng

# CREATOR
dct_creator_sm:
- Brown University Library

# PUBLISHER
dct_publisher_sm:
- Rhode Island Department of Education
- Rhode Island Department of Transportation

# PROVIDER
schema_provider_s: Brown

# RESOURCE CLASS
gbl_resourceClass_sm: 
- Datasets

# RESOURCE TYPE
gbl_resourceType_sm:
- Point data

# LC SUBJECT
dct_subject_sm:
- Education
- Schools
- Elementary schools
- High schools

# ISO THEME
dcat_theme_sm:
- Society
- Structure

# TEMPORAL
dct_temporal_sm:
- '2024'
- 21st century

# DATE ISSUED
dct_issued_s: '2024-05'

# SPATIAL
dct_spatial_sm:
- Rhode Island, United States

# BOUNDING BOX
dcat_bbox: 'ENVELOPE(-71.9073,-71.0886,42.0189,41.0958)'

# RIGHTS
dct_rights_sm: 
- The data are licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. You are free to share and to adapt the work as long as you cite the source, do not use it for commercial purposes, and release adaptations under the same license.
- Disclaimer. Every effort was made to ensure that the data, which was compiled from public sources, was processed and presented accurately. The creators and Brown University disclaim any liability for errors, inaccuracies, or omissions that may be contained therein or for any damages that may arise from the foregoing. Users should independently verify the accuracy and fitness of the data for their purposes.

# LICENSE
dct_license_sm:
- https://creativecommons.org/licenses/by-nc-sa/4.0/

# ACCESS RIGHTS
dct_accessRights_s: Public

# FILE FORMAT
dct_format_s: SQLite

# UNIQUE ID
id: brown-04172024AAI

# IDENTIFIER
dct_identifier_sm:
- https://github.com/Brown-University-Library/geodata_ossdb

# METADATA MODIFIED
gbl_mdModified_dt: '2024-04-17'

# METADATA VERSION
gbl_mdVersion_s: Aardvark

# GEOREFERENCED
gbl_georeferenced_b: True